version: 2
updates:
  - package-ecosystem: gomod
    directory: /services/state-service
    schedule:
      interval: weekly
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /services/state-service
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
